version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

jobs:
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint webapp with Flake8 and black
          command: flake8 canonicalwebteam tests && black --line-length 79 --check canonicalwebteam tests
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python3-venv
            pip3 install poetry
            poetry install
      - run:
          name: Run Python tests
          command: poetry run python -m unittest discover tests

workflows:
  version: 2
  build:
    jobs:
      - lint-python
      - test-python