name: Flask Base

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-18.04
   
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: pip3 install black flake8

    - name: Flake
      run: flake8 canonicalwebteam tests

    - name: Black
      run: black --line-length 79 --check canonicalwebteam tests
  
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: pip3 install .

    - name: Test
      run: python3 -m unittest discover tests

